version: "3.8"

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    restart: always

  redis:
    image: "redis"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - app

  celery_worker:
    container_name: celery_worker
    build: .
    command:  celery -A celery_worker.celery worker -B --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A celery_worker.celery flower --port=5555
    ports:
      - "5556:5555"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis
      - celery_worker
